### PR TITLE
v2.0

### PR DESCRIPTION
**Pull request by jeduan**
So I went ahead and started refactoring some stuff and one thing led to the other and ended up migrating the whole thing to ES6. There's obviously many new stuff, but I'll try to summarize my thinking behind.

 - Using [Bluebird](https://www.npmjs.com/package/bluebird) promises now instead of [async](https://www.npmjs.com/package/async). I was having many problems with consolidate [sending double callbacks after an error](https://github.com/tj/consolidate.js/issues/143)
 - Now using directly consolidate to render. This means we can support any rendering engine supported upstream such as React, haml and lodash.
 - New class called `EmailTemplate` that automatically caches a single template directory.

That said, I'm assigning the major version bump to this because I'm removing some stuff (though all tests pass)

 - The support for exporting a zlib buffer was removed. I saw no tests for this and no public API, so I'm not sure how much it's being used. In my mind this belongs to other library.
 - Emblem is being deprecated as a template library. It doesn't seem to be maintained anymore and it was not possible for me to find a way to reliably test both Handlebars and this template library.

Since this is a big change I'd like community input. I'm releasing this beta on npm and hopefully you will help testing with your templates and reporting any bugs.

### CODE REVIEW

**Comment by ArdentZeal** [comment]
I would like to add 2 things which annoy me to no end and with all the breaking changes now might be a good time.

I would propose to move the file ending format parsing to change to following behaviour to be able to handle the files like you would expect on the OS. (right programs can be used and do not have to be selected manually)

<filename>.templateengine.html
<filename>.templateengine.txt
<filename>.css(.preprocessor)

I also would like to see an option to have a subject file, which can be run through the templateengine. Something like

<filename>.templateengine.subject.txt

I could also code the PR for it, but I would like to have some feedback first before doing the work.

Kind Regards

**Comment by jeduan** [comment]
@ArdentZeal I like the subject idea a lot. Not sure about the naming, given that some engines like jade/hbs expect filenames to end in `.jade`. You can fiddle with the globs in https://github.com/niftylettuce/node-email-templates/blob/v2.0/src/util.js#L21 to try to find something that works for you, tho.

**Comment by eddywashere** [comment]
Stumbled across this pr and  ended up using 2.0 over at https://github.com/eddywashere/node-prelaunch/tree/d36eb2007794fa647d6a7e3ec346980471a7d7ee/server/email

So far so good. Just a little feedback

- when I make a css change I have to make it across all template directories. I might use something like `_shared.scss` to reference a shared stylesheet. would be nice to have a relative link to a common stylesheet from the template.
- more documentation for template options. I'm using swig and could not figure out how to pass swig options in and have them picked up. I wanted to specify layout directory and change comment delimiters (<- would like my html comments stripped from sent emails).

**Comment by jeduan** [comment]
Thank you for your feedback! Definitely writing more docs and examples before merging.

**Pull request merged**
