### PR TITLE
Added option for overriding template engine setting

### PR DESCRIPTION
**Pull request by linusbrolin**
Some template engines (for example: htmling) do not use their name as file extension, and instead use regular html extensions.
This patch makes it possible to provide the engine name through the locals object instead, which also makes it possible to use .html for the template files.

### CODE REVIEW

**Comment by jeduan** [comment]
Thanks for the PR! Can you fix the tests not passing?

**Comment by linusbrolin** [comment]
Finally made it work with all tests.
Was a bit more involved than I thought, but now it should be possible to provide an object (locals.engines) where you can override the engine per file extension.

**Comment by jayagl** [comment]
Any updates on merging this?

**Comment by niftylettuce** [comment]
Is the readme here updated to reflect these changes? @linusbrolin

**Comment by linusbrolin** [comment]
@niftylettuce sorry, I missed your ping.
If you're still interested in this then I can take a look at it again.

**Pull request closed without merging**
