### PR TITLE
Ability to use the node-sass data option 

### PR DESCRIPTION
**Pull request by sunild**
This change avoids overwriting any sass that you pass via the `data` option for node-sass. I'm using it to pass in dynamic sass variable values (for themes, etc).

### CODE REVIEW

**Comment by niftylettuce** [comment]
Are either of you interested in helping to maintain this repo? @timelf123 @sunild

**Comment by timelf123** [comment]
I can help out here and there but given my previous commitments, will not be able to be a "main" contributor if that makes sense @niftylettuce

**Comment by sunild** [comment]
apologies for chiming in so late, I wouldn't be able to commit enough time to it either I'm afraid

**Comment by niftylettuce** [comment]
@timelf123 @sunild Can you see https://github.com/crocodilejs/node-email-templates/pull/229/commits/f8b2ad285ae53394544fb869a429af108a40bc6d and resolve conflicts / merge your work?  If you fix issues and check that commit then send me a comment here once you're done I will merge / release.

**Pull request closed without merging**
