### PR TITLE
Support template for email subject

### PR DESCRIPTION
**Pull request by snow01**
We often need template support for email subject too.

### CODE REVIEW

**Comment by snow01** [comment]
CI Build is failing on some test case not updated and affected by my code. See below --

```
1) Email templates should render html(jade) with inline CSS(less):
      Uncaught AssertionError: expected '<h4 style="color: #ccc;">test</h4>' to equal '<h4 style="color: #cccccc;">test</h4>'
      + expected - actual
      -<h4 style="color: #ccc;">test</h4>
      +<h4 style="color: #cccccc;">test</h4>
```

**Comment by gilbertwyw** [comment]
It would be useful as my current project requires "subject" to be of different languag. But "subject" is not part of the template. I can make `email-template` package lookup different language folder that contain a meta data file. But this PR solves the problem much better.

**Comment by snow01** [comment]
@gilbertwyw - thanks !

Most of the time we need to customise subject with same data (variables) as the body - so it does make sense to use the same template system for both cases.

**Comment by niftylettuce** [comment]
Can you please rebase into one commit?

**Comment by ebourmalo** [comment]
I would really appreciate this feature as well :)

**Comment by snow01** [comment]
Okay, let me rebase and resubmit. Pull request kept waiting for months, and then I stopped following.

**Comment by ebourmalo** [comment]
@snow01 Any update on this :) ?

**Comment by snow01** [comment]
As there were some changes in upstream, created a new pull request: https://github.com/niftylettuce/node-email-templates/pull/164

Hope to see this getting merged soon.

Will discard this pull request.

**Pull request closed without merging**
