### PR TITLE
Add suport to sub folders for localization

### PR DESCRIPTION
**Pull request by albertosouza**
I added the localization feature build in https://github.com/albertosouza/email-templates-i18n here with tests and support for older non localized versions

Need more reviews.

Ref https://github.com/niftylettuce/node-email-templates/issues/171

### CODE REVIEW

**Comment by niftylettuce** [comment]
Is it possible you could fix conflicts?  We definitely would love to have this 100%.  I'd even give you a donation over PayPal if you could get this in!

**Comment by albertosouza** [comment]
Ok @niftylettuce , i have some time now.
i Will take a look.

**Comment by albertosouza** [comment]
Updates:
- Rebased with master
- Merged with old postrequest for keep track
- render fixed
- handlebars example updated, now it are working and log 2 versions of i18n email

Local testes are passing but lets see if it passes in travis tests

**Comment by albertosouza** [comment]
@niftylettuce done

**Pull request merged**
