### PR TITLE
Support 0.12

### PR DESCRIPTION
**Pull request by jeduan**
Uses latest node-sass, consolidate and juice to support 0.12

 - Migrates back to upstream Juice
 - Travis now supports 0.12 and io.js

### CODE REVIEW

**Comment by jeduan** [comment]
@niftylettuce please take a look and if good let's go ahead and close a lot of issues.

**Comment by mike-spainhower** [comment]
:+1: I have switched to 0.12 and got bit by this.  Wasted a bit of time assuming it was a bug in my project.

**Comment by shettysuraj** [comment]
Looks good to me :+1:

**Comment by mike-spainhower** [comment]
Awesome thanks!! :love_hotel:   What is the release cycle to the npm registry?

**Comment by jeduan** [comment]
Published as 1.2.0 in npm

**Pull request merged**
