### PR TITLE
Adding inky support

### PR DESCRIPTION
**Pull request by jongon**
Added Inky support, when you write html using foundation emails framework (inky) first you compile your html and before applying styles it compiles html with inky pre processor

### CODE REVIEW

**Comment by niftylettuce** [comment]
@jongon interested in being a maintainer?

**Comment by jongon** [comment]
@niftylettuce, yes i would like to be a maintainer to this package, what do you think about this pull request?

**Comment by homerjam** [comment]
I also need Inky - my PR #190 adds Inky support too (and more potentially)

**Comment by homerjam** [comment]
Hi @jongon could you please test #190 and see if it satisfies your needs?

**Comment by niftylettuce** [comment]
Can this be closed now that #190 is merged and released?

**Comment by snics** [comment]
@niftylettuce wanted to ask you if the inky support is there. If so how can I use it?

**Pull request closed without merging**
