### PR TITLE
fix(renderLess): support less 2.0

### LINKED ISSUE #103: Less compilation fails with Less > 2.0
It looks like Less version 1.7.5 works fine but any Less version greater than 2.0 fails. The Less 2.0 release documentation seems to indicate that the method accessing the .parse() function has changed. Probably just need to look into the changes to less.parse() and adapt accordingly.

### PR DESCRIPTION
**Pull request by kingcody**
Changes:
- use less.render for a cross-version solution

Closes #103

### CODE REVIEW

**Comment by kingcody** [comment]
It would seem that the issues with the tests failing on node `v0.11.14` are related to tj/consolidate.js#143

Any ideas on a solution?

**Comment by jeduan** [comment]
Thank you for this? Can you please rebase?

**Comment by chamerling** [comment]
Hi @kingcody, all,
Any news on that? Thanks!

**Comment by kingcody** [comment]
I'll do a rebase tonight :)

**Comment by kingcody** [comment]
@jeduan any idea whats up with the `libsass` error on iojs build?

**Comment by kingcody** [comment]
Other than that, it should be good (rebased and what not).

**Comment by kingcody** [comment]
Ok, turns out `node-sass` doesn't support iojs > 1.2 ATM. Switched to 1.2.0 in `.travis.yml`.

**Pull request merged**
